5.¿Cuáles son las diferencias entre los siguientes métodos?
```ruby
def opcion_1
  a = [1, nil, 3, nil, 5, nil, 7, nil, 9, nil]
  b = 3
  c = a.map do |x|
    x * b
  end
  puts c.inspect
rescue
  0
end

def opcion_2
  c = begin
        a = [1, nil, 3, nil, 5, nil, 7, nil, 9, nil]
        b = 3
        a.map do |x|
          x * b
        end
      rescue
        0
      end
  puts c.inspect
end

def opcion_3
  a = [1, nil, 3, nil, 5, nil, 7, nil, 9, nil]
  b = 3
  c = a.map { |x| x * b } rescue 0
  puts c.inspect
end

def opcion_4
  a = [1, nil, 3, nil, 5, nil, 7, nil, 9, nil]
  b = 3
  c = a.map { |x| x * b rescue 0 }
  puts c.inspect
end
```

### Primero, vemos los resultados de ejecucion
```
irb(main):011:0> opcion_1
=> 0
```

```
irb(main):024:0> opcion_2
0
=> nil
```

```
irb(main):038:0> opcion_3
0
=> nil
```

```
irb(main):039:0> opcion_4
[3, 0, 9, 0, 15, 0, 21, 0, 27, 0]
=> nil
```

### Analizamos
* En opcion_1 se produce una excepcion cuando se recorre el array, por ende el metodo termina y tipo se propaga la excepcion en el siguiente nivel. No se hace put.
* En opcion_2, como se genera la excepcion, lo que esta abajo del rescue (puts) nunca se ejecuta
* En opcion_3 pasa lo mismo que arriba
* En opcion_4 al poner el rescue adentro del bloque que itera sobre el array, si se produce una excepcion sale de ese bloque, se ejecuta el manejador, y tipo si se imprime porque sigue abajo, no es que se termina el metodo. 